[build]
  command = "npm run build"
  publish = ".next"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy= " midi=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), fullscreen=(), payment=()"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://accounts.google.com; style-src 'self' https://fonts.googleapis.com https://accounts.google.com 'unsafe-inline'; img-src 'self' data: https://poklist-be-dev-399453774973.asia-east1.run.app; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.google.com https://www.googleapis.com https://poklist-be-dev-399453774973.asia-east1.run.app https://relist-dev-23771036426.asia-east1.run.app https://dev-api.relist.cc; frame-src 'self' https://accounts.google.com; frame-ancestors 'none';"
