export const Idea = {
  DEFAULT_FIRST_BATCH_OFFSET: 0,
  MAX_BATCH_SIZE: 99,
  DEFAULT_FIRST_BATCH_SIZE: 3,
  // DEFAULT_BATCH_SIZE: 10,
  DEFAULT_BATCH_SIZE: 99,
} as const;

export const List = {
  DEFAULT_FIRST_BATCH_OFFSET: 0,
  MAX_BATCH_SIZE: 99,
  DEFAULT_FIRST_BATCH_SIZE: 3,
  // DEFAULT_BATCH_SIZE: 10,
  DEFAULT_BATCH_SIZE: 99,
} as const;

export const DAY_IN_MS = 86400000;
export const RECENTLY_UPDATED_DAYS = 7;

export const DESCRIPTION_PREVIEW_LENGTH = 20;
export const LINK_PREVIEW_LENGTH = 40;
